cache:
  paths:
    - .cache

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"

stages:
  - test
  - smoke-test
  - build
  - deploy

unit:
  image: docker/compose:1.25.0-rc2-alpine
  stage: test
  except:
    - master
  variables:
    GOPATH: "~"
  services:
    - docker:19-dind
  tags:
    - midgard
  before_script:
    - echo $GOPATH
    - apk update
    - apk add make curl bash
  script:
    - make test

lint:
  image: golangci/golangci-lint
  stage: test
  except:
    - master
  tags:
    - midgard
  before_script:
    - go get mvdan.cc/gofumpt
  script:
    - make lint-verbose

smoke-test:
  stage: smoke-test
  image: docker/compose:alpine-1.25.4
  services:
    - docker:19-dind
  tags:
    - midgard
  artifacts:
    when: on_failure
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./logs/
  before_script:
    - apk update
    - apk add make git jq curl
    - make docker-gitlab-master
    - git clone --single-branch -b $CI_COMMIT_BRANCH https://gitlab.com/thorchain/thornode.git || git clone --single-branch -b master https://gitlab.com/thorchain/thornode.git
    - cd thornode
    - test master = $(git rev-parse --abbrev-ref HEAD) && docker pull registry.gitlab.com/thorchain/thornode:mocknet
    - make -C build/docker reset-mocknet-standalone
  except:
    - schedules
  environment:
    name: develop
  script:
    - git clone --single-branch -b $CI_COMMIT_BRANCH https://gitlab.com/thorchain/heimdall.git || git clone --single-branch -b master https://gitlab.com/thorchain/heimdall.git
    - cd ./heimdall
    - make build
    - make smoke
  after_script:
    - ./thornode/scripts/docker_logs.sh

# Build docker image for master branch as latest
build-master:
  stage: build
  image: docker:stable
  tags:
    - midgard
  only:
    - master
  services:
    - docker:19-dind
  before_script:
    - apk update
    - apk add make git jq curl
    - make docker-gitlab-login
  script:
    - make docker-gitlab-master

# Build docker image for release using git tag
build-release:
  stage: build
  image: docker:stable
  tags:
    - midgard
  only:
    - tags
  services:
    - docker:19-dind
  before_script:
    - apk update
    - apk add make git jq curl
    - make docker-gitlab-login
  script:
    - make docker-gitlab-release
